apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: sgi
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sgi-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.mongoPassword | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sgi-config
  namespace: {{ .Values.global.namespace }}
data:
  MONGO_HOST: "mongodb://sgi-mongodb:{{ .Values.mongodb.port }}"
  MONGO_DB: "sgi_db"
  POSTGRES_HOST: "sgi-postgresql"
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  REDIS_HOST: "redis://sgi-redis:{{ .Values.redis.port }}/0"
  OLLAMA_HOST: "http://sgi-ollama:{{ .Values.ollama.port }}"
  CORS_ORIGINS: '["https://{{ .Values.ingress.hostname }}"]'
  DEBUG: "false"
